### PR TITLE
Add relationship between contact, uf_match, and users.

### PR DESCRIPTION
**Pull request by puresyntax71**
Related to #204.

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
@dsnopek any thoughts about this one? Seems pretty cut and dry to me. Once this is merged, and we have the >processViewsDataForSpecialFields() method in the codebase, we can submit several more improvements

**Comment by jackrabbithanna** [comment]
For https://github.com/eileenmcnaughton/civicrm_entity/issues/206

**Comment by dsnopek** [comment]
Yeah, this seems fine to me.

**Comment by jackrabbithanna** [comment]
Merging #213

**Pull request merged**
