### PR TITLE
Must be more specific about CiviCRM versions.

### PR DESCRIPTION
**Pull request by KarinG**
Before
----------------------------------------
Testing using 5.41.2 -> 4 times

After
----------------------------------------
Testing using 5.35.* 5.39.* RC and dev-master

Technical Details
----------------------------------------
Need the * or it will resolve to latest stable

### CODE REVIEW

**Comment by KarinG** [comment]
Ah right it needs a fix for -> 
`#6 /home/runner/drupal/vendor/scssph in /home/runner/drupal/vendor/scssphp/scssphp/src/Compiler.php on line 553`

Coming up

**Comment by KarinG** [comment]
Ok so that proved that these tests were running against 5.41 (the scss issue was fixed in 5.41).

**Comment by jackrabbithanna** [comment]
Yep, good PR. Silly me updating the versions. Can merge on test pass

**Comment by KarinG** [comment]
Is there something in your civicrm-entity composer.json that we hit here -> 
`    - drupal/civicrm_entity 3.0.0-beta1 requires drupal/civicrm * -> no matching package found.`

PS - these are real test failures now.

**Comment by jackrabbithanna** [comment]
We hadn't had problems with the composer.json before this.

**Comment by jackrabbithanna** [comment]
We have had trouble with composer conflicts for Drupal 8.9 and CiviCRM 5.39 and above. We're upgrading to Drupal 9 on sites to use 5.39 and above, mainly because it needs to be done anyway, considering D8 EOL is November 2nd, 2021
But it is still good to figure out and support D8 with tests and CE, at least for several more months.

**Comment by KarinG** [comment]
Composer is correct in that there is no `drupal/civicrm` package. But I don't think that's what it choked on. I had an extra trailing comma. It's building now.

**Comment by jackrabbithanna** [comment]
I guess the change to the composer.json is ok. I know it needs 5.13 or above, but honestly, people should be using at least that version already.

**Comment by KarinG** [comment]
And we are ✅ and now testing on all currently relevant versions.

**Comment by jackrabbithanna** [comment]
Thanks Karin!!!
Merging #333

**Pull request merged**
