### PR TITLE
…

### PR DESCRIPTION
**Pull request by stevenvdhout**
Use the getFields method from civicrmApi to pass allong all the field names inside the get method.
Also transforms dates to timestamps and vice versa.

This makes the content inside custom fields from CiviCRM available in Drupal.

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
I like this as a beginning to adding custom fields support, but will have to take into consideration multi-valued custom fields at some point.

@mglaman 
Do you think changing the date fields to timestamps breaks anything you add done. Want to take a glance at this?

**Comment by mglaman** [comment]
Converting to timestamps probably simplifies things. Looked on mobile and looks fine.

In currently reviewing how we can support custom Drupal fields, and this looks like there's no conflict. This just improves the Civi API integration

**Comment by jackrabbithanna** [comment]
Merging #149

**Comment by jackrabbithanna** [comment]
pushed to 8.x-3.x-dev on D.O project page

**Pull request merged**
