### PR TITLE
Fix field labels

### PR DESCRIPTION
**Pull request by caracolmzd**
fixes #18 - create function to be more flexible about the title field in the schema.

### CODE REVIEW

**Comment by caracolmzd** [comment]
sorry, contains commits from PR https://github.com/eileenmcnaughton/civicrm_entity/pull/17
Should work fine if you merge the other first, but let me know if I should re-PR.

**Comment by eileenmcnaughton** [comment]
Michael - should this still be live? You closed one PR - I think this one & the other one are ok too now?

**Comment by caracolmzd** [comment]
@eileenmcnaughton I think it is still relevant. See the new function added and it's usage. I cleaned up the PR to remove the extraneous commits and rebased it to the current state of 7.x.1.x

**Comment by eileenmcnaughton** [comment]
did you look at branch 2 or only branch 1? ( I can't recall where things are at but 2 has more stuff than 1)

**Comment by eileenmcnaughton** [comment]
I merged it through from 7.1 -just after posting

**Pull request merged**
