### PR TITLE
Use single entity class

### PR DESCRIPTION
**Pull request by mglaman**

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
@mglaman Is PR #136 still necessary, I see you have a commit here in this PR removing display suite information.

I'm going to merge this, I trust this is good, and we'll let people test this and comment and/or add PRs of their own if they want to change something. Thanks again for contributing.

**Comment by dsnopek** [comment]
FYI, just reviewed this waaay after the fact and I have no comments on this PR - save for a couple commented out debugging lines, it all looks good to me!

**Comment by jackrabbithanna** [comment]
awesome @dsnopek I've been just kinda waiting and see what infrastructure gets created by the Matt the D8 entity genius here before thinking about having 2 cents to add..Since there's no releases or anything, if he wants it merged, its getting merged....I did push a 8.x-3.x-dev release to the drupal.org project page.....

**Comment by jackrabbithanna** [comment]
I've added myDropWizard as a supporting organization to the project page as well...let me know if you want something put on the page there, or should list a different organization

**Pull request merged**
