### PR TITLE
Add a GitHub Actions workflow for automated testing

### PR DESCRIPTION
**Pull request by mglaman**
Overview
----------------------------------------
Adds a GitHub Actions workflow, borrowed from webform_civicrm so we can start adding test coverage.

No functional changes

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
I'm going to merge this immediately, and it can be iterated upon if necessary. No impact to module users downstream.

**Comment by mglaman** [comment]
Thanks, @jackrabbithanna! This will help me start squashing things and hopefully cut down on the feedback loop for various things!

**Comment by mglaman** [comment]
@jackrabbithanna I'm going to convert the existing Kernel tests to Functional tests, since SupportedEntities isn't stateless anymore, which is why it is failing

**Comment by jackrabbithanna** [comment]
Go for it, I perceive this as a learning opportunity. Thanks Matt!

**Pull request merged**
