### PR TITLE
better formatter code organization, some contribution entity fields display formatters

### PR DESCRIPTION
**Pull request by jackrabbithanna**
also a better way to do the link formatters...

and bug fixes

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
merging - NB I'm pretty sure you can determine yes_no_fields from the schema metadata / getfields result for a given api

**Comment by jackrabbithanna** [comment]
I could use a code example....The $fields array in those functions don't have any information about meta data.  I couldn't think of a way to automate further whether a fields should have yes/no formatters, link formatters, or option value formatters....Please stop me if there's a better way because I plan on pushing forward with the rest of the entities

**Comment by jackrabbithanna** [comment]
of course what about custom fields...that would need some automation...

I'm trying to do this as quickly as I can for a 2.x release, and holidays are the only time I have off.

**Comment by jackrabbithanna** [comment]
```
$result = civicrm_api3('Contact', 'getfields', array(
'sequential' => 1,
));
```

when i do a getfields api call on a field, i see two bits of information
$result[values][x]['type']
and $result[values][x]['html']['type]

neither of which tells me much about how the field could/should be displayed......

The type is simply whether it is integer, text, or datetime.

As for the HTML type?
Could I say that all 'Select' are option lists? Could all fields with Checkbox html types be yes/no or true/false?

**Comment by eileenmcnaughton** [comment]
Yes, all select fields are option lists and boolean has it's own type (class CRM_Utils_Type::T_Bool). You might be better not using sequential => 1 with getfields - the keys are fieldnames so could be useful.

You can get the options for any field using the getoptions api - at least for custom fields checkboxes could be other than boolean so that would be useful

**Pull request merged**
