### PR TITLE
civi case support

### PR DESCRIPTION
**Pull request by jackrabbithanna**
Also I fixed a bug that was occuring when I was trying to view the label of entities referenced using entity reference fields, in Views. 

check out the else clause in function_civicrm_entity_access line 67

I call the other entity access callback to handle the cases better than just defaulting to "administer CiviCRM"

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
Wondering if you wanted CiviCase support, and this bugfix to make it into the main branch....

I'm working on some new stuff as well.....

**Comment by jackrabbithanna** [comment]
Added support for CustomField and CustomGroup entities
Fixed display suite integration so that layout css is loaded when entity is viewed
reorganized code, put the form stuff in its own file
put the display suite stuff in its own file
fixed a couple of notices

**Comment by eileenmcnaughton** [comment]
Hey Mark, sorry I've only been partly following due to workload. Is this ready for merge now? Is this the point where we should change version?

**Comment by jackrabbithanna** [comment]
I think everything that is this pull request could stay in the 2.0 branch....I'm working on a different approach to custom fields, but i"m doing that in a separate module for now, and it may require a patch to the Drupal Entity API module....I'm experimenting with some different ideas...These commits fixes a couple of bugs, does a bit of code reorganization, and exposes CustomField and CustomGroup entities to Drupal.  I need these exposed for the future work that I'm doing....which may include adding custom groups and fields from the Drupal Manage Fields page.....

**Comment by jackrabbithanna** [comment]
FYI: https://github.com/jackrabbithanna/civicrm_entity_custom_values
Requires the modified Entity API module ATM....provided in the repo

**Comment by eileenmcnaughton** [comment]
Ok - do you want me to merge this now - or hold off for a bit longer?

**Pull request merged**
